#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomZdravlja.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DomZdravljaDB")]
	public partial class DomZdravljaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblIzvestaj(tblIzvestaj instance);
    partial void UpdatetblIzvestaj(tblIzvestaj instance);
    partial void DeletetblIzvestaj(tblIzvestaj instance);
    partial void InserttblSluzba(tblSluzba instance);
    partial void UpdatetblSluzba(tblSluzba instance);
    partial void DeletetblSluzba(tblSluzba instance);
    partial void InsertZaposleni(Zaposleni instance);
    partial void UpdateZaposleni(Zaposleni instance);
    partial void DeleteZaposleni(Zaposleni instance);
    #endregion
		
		public DomZdravljaDBDataContext() : 
				base(global::DomZdravlja.DataAccess.Properties.Settings.Default.DomZdravljaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DomZdravljaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomZdravljaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomZdravljaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomZdravljaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblIzvestaj> tblIzvestajs
		{
			get
			{
				return this.GetTable<tblIzvestaj>();
			}
		}
		
		public System.Data.Linq.Table<tblSluzba> tblSluzbas
		{
			get
			{
				return this.GetTable<tblSluzba>();
			}
		}
		
		public System.Data.Linq.Table<Zaposleni> Zaposlenis
		{
			get
			{
				return this.GetTable<Zaposleni>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblIzvestaj")]
	public partial class tblIzvestaj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IzvestajID;
		
		private int _SluzbaID;
		
		private string _NazivIzvestaja;
		
		private int _BrojPacijenata;
		
		private System.DateTime _DatumKreiranja;
		
		private EntityRef<tblSluzba> _tblSluzba;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIzvestajIDChanging(int value);
    partial void OnIzvestajIDChanged();
    partial void OnSluzbaIDChanging(int value);
    partial void OnSluzbaIDChanged();
    partial void OnNazivIzvestajaChanging(string value);
    partial void OnNazivIzvestajaChanged();
    partial void OnBrojPacijenataChanging(int value);
    partial void OnBrojPacijenataChanged();
    partial void OnDatumKreiranjaChanging(System.DateTime value);
    partial void OnDatumKreiranjaChanged();
    #endregion
		
		public tblIzvestaj()
		{
			this._tblSluzba = default(EntityRef<tblSluzba>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzvestajID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IzvestajID
		{
			get
			{
				return this._IzvestajID;
			}
			set
			{
				if ((this._IzvestajID != value))
				{
					this.OnIzvestajIDChanging(value);
					this.SendPropertyChanging();
					this._IzvestajID = value;
					this.SendPropertyChanged("IzvestajID");
					this.OnIzvestajIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SluzbaID", DbType="Int NOT NULL")]
		public int SluzbaID
		{
			get
			{
				return this._SluzbaID;
			}
			set
			{
				if ((this._SluzbaID != value))
				{
					if (this._tblSluzba.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSluzbaIDChanging(value);
					this.SendPropertyChanging();
					this._SluzbaID = value;
					this.SendPropertyChanged("SluzbaID");
					this.OnSluzbaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivIzvestaja", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivIzvestaja
		{
			get
			{
				return this._NazivIzvestaja;
			}
			set
			{
				if ((this._NazivIzvestaja != value))
				{
					this.OnNazivIzvestajaChanging(value);
					this.SendPropertyChanging();
					this._NazivIzvestaja = value;
					this.SendPropertyChanged("NazivIzvestaja");
					this.OnNazivIzvestajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojPacijenata", DbType="Int NOT NULL")]
		public int BrojPacijenata
		{
			get
			{
				return this._BrojPacijenata;
			}
			set
			{
				if ((this._BrojPacijenata != value))
				{
					this.OnBrojPacijenataChanging(value);
					this.SendPropertyChanging();
					this._BrojPacijenata = value;
					this.SendPropertyChanged("BrojPacijenata");
					this.OnBrojPacijenataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumKreiranja", DbType="Date NOT NULL")]
		public System.DateTime DatumKreiranja
		{
			get
			{
				return this._DatumKreiranja;
			}
			set
			{
				if ((this._DatumKreiranja != value))
				{
					this.OnDatumKreiranjaChanging(value);
					this.SendPropertyChanging();
					this._DatumKreiranja = value;
					this.SendPropertyChanged("DatumKreiranja");
					this.OnDatumKreiranjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSluzba_tblIzvestaj", Storage="_tblSluzba", ThisKey="SluzbaID", OtherKey="SluzbaID", IsForeignKey=true)]
		public tblSluzba tblSluzba
		{
			get
			{
				return this._tblSluzba.Entity;
			}
			set
			{
				tblSluzba previousValue = this._tblSluzba.Entity;
				if (((previousValue != value) 
							|| (this._tblSluzba.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSluzba.Entity = null;
						previousValue.tblIzvestajs.Remove(this);
					}
					this._tblSluzba.Entity = value;
					if ((value != null))
					{
						value.tblIzvestajs.Add(this);
						this._SluzbaID = value.SluzbaID;
					}
					else
					{
						this._SluzbaID = default(int);
					}
					this.SendPropertyChanged("tblSluzba");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSluzba")]
	public partial class tblSluzba : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SluzbaID;
		
		private string _NazivSluzbe;
		
		private string _OpisSluzbe;
		
		private System.DateTime _DatumOsnivanja;
		
		private EntitySet<tblIzvestaj> _tblIzvestajs;
		
		private EntitySet<Zaposleni> _Zaposlenis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSluzbaIDChanging(int value);
    partial void OnSluzbaIDChanged();
    partial void OnNazivSluzbeChanging(string value);
    partial void OnNazivSluzbeChanged();
    partial void OnOpisSluzbeChanging(string value);
    partial void OnOpisSluzbeChanged();
    partial void OnDatumOsnivanjaChanging(System.DateTime value);
    partial void OnDatumOsnivanjaChanged();
    #endregion
		
		public tblSluzba()
		{
			this._tblIzvestajs = new EntitySet<tblIzvestaj>(new Action<tblIzvestaj>(this.attach_tblIzvestajs), new Action<tblIzvestaj>(this.detach_tblIzvestajs));
			this._Zaposlenis = new EntitySet<Zaposleni>(new Action<Zaposleni>(this.attach_Zaposlenis), new Action<Zaposleni>(this.detach_Zaposlenis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SluzbaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SluzbaID
		{
			get
			{
				return this._SluzbaID;
			}
			set
			{
				if ((this._SluzbaID != value))
				{
					this.OnSluzbaIDChanging(value);
					this.SendPropertyChanging();
					this._SluzbaID = value;
					this.SendPropertyChanged("SluzbaID");
					this.OnSluzbaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivSluzbe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivSluzbe
		{
			get
			{
				return this._NazivSluzbe;
			}
			set
			{
				if ((this._NazivSluzbe != value))
				{
					this.OnNazivSluzbeChanging(value);
					this.SendPropertyChanging();
					this._NazivSluzbe = value;
					this.SendPropertyChanged("NazivSluzbe");
					this.OnNazivSluzbeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpisSluzbe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string OpisSluzbe
		{
			get
			{
				return this._OpisSluzbe;
			}
			set
			{
				if ((this._OpisSluzbe != value))
				{
					this.OnOpisSluzbeChanging(value);
					this.SendPropertyChanging();
					this._OpisSluzbe = value;
					this.SendPropertyChanged("OpisSluzbe");
					this.OnOpisSluzbeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumOsnivanja", DbType="Date NOT NULL")]
		public System.DateTime DatumOsnivanja
		{
			get
			{
				return this._DatumOsnivanja;
			}
			set
			{
				if ((this._DatumOsnivanja != value))
				{
					this.OnDatumOsnivanjaChanging(value);
					this.SendPropertyChanging();
					this._DatumOsnivanja = value;
					this.SendPropertyChanged("DatumOsnivanja");
					this.OnDatumOsnivanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSluzba_tblIzvestaj", Storage="_tblIzvestajs", ThisKey="SluzbaID", OtherKey="SluzbaID")]
		public EntitySet<tblIzvestaj> tblIzvestajs
		{
			get
			{
				return this._tblIzvestajs;
			}
			set
			{
				this._tblIzvestajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSluzba_Zaposleni", Storage="_Zaposlenis", ThisKey="SluzbaID", OtherKey="SluzbaId")]
		public EntitySet<Zaposleni> Zaposlenis
		{
			get
			{
				return this._Zaposlenis;
			}
			set
			{
				this._Zaposlenis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblIzvestajs(tblIzvestaj entity)
		{
			this.SendPropertyChanging();
			entity.tblSluzba = this;
		}
		
		private void detach_tblIzvestajs(tblIzvestaj entity)
		{
			this.SendPropertyChanging();
			entity.tblSluzba = null;
		}
		
		private void attach_Zaposlenis(Zaposleni entity)
		{
			this.SendPropertyChanging();
			entity.tblSluzba = this;
		}
		
		private void detach_Zaposlenis(Zaposleni entity)
		{
			this.SendPropertyChanging();
			entity.tblSluzba = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zaposleni")]
	public partial class Zaposleni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ime;
		
		private string _Prezime;
		
		private System.DateTime _DatumZaposlenja;
		
		private int _SluzbaId;
		
		private string _Email;
		
		private EntityRef<tblSluzba> _tblSluzba;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnDatumZaposlenjaChanging(System.DateTime value);
    partial void OnDatumZaposlenjaChanged();
    partial void OnSluzbaIdChanging(int value);
    partial void OnSluzbaIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Zaposleni()
		{
			this._tblSluzba = default(EntityRef<tblSluzba>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumZaposlenja", DbType="Date NOT NULL")]
		public System.DateTime DatumZaposlenja
		{
			get
			{
				return this._DatumZaposlenja;
			}
			set
			{
				if ((this._DatumZaposlenja != value))
				{
					this.OnDatumZaposlenjaChanging(value);
					this.SendPropertyChanging();
					this._DatumZaposlenja = value;
					this.SendPropertyChanged("DatumZaposlenja");
					this.OnDatumZaposlenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SluzbaId", DbType="Int NOT NULL")]
		public int SluzbaId
		{
			get
			{
				return this._SluzbaId;
			}
			set
			{
				if ((this._SluzbaId != value))
				{
					if (this._tblSluzba.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSluzbaIdChanging(value);
					this.SendPropertyChanging();
					this._SluzbaId = value;
					this.SendPropertyChanged("SluzbaId");
					this.OnSluzbaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSluzba_Zaposleni", Storage="_tblSluzba", ThisKey="SluzbaId", OtherKey="SluzbaID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblSluzba tblSluzba
		{
			get
			{
				return this._tblSluzba.Entity;
			}
			set
			{
				tblSluzba previousValue = this._tblSluzba.Entity;
				if (((previousValue != value) 
							|| (this._tblSluzba.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSluzba.Entity = null;
						previousValue.Zaposlenis.Remove(this);
					}
					this._tblSluzba.Entity = value;
					if ((value != null))
					{
						value.Zaposlenis.Add(this);
						this._SluzbaId = value.SluzbaID;
					}
					else
					{
						this._SluzbaId = default(int);
					}
					this.SendPropertyChanged("tblSluzba");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
